apiVersion: v1
kind: Service
metadata:
  name: jmblog-api-ci141
  labels:
    app: jmblog-api
    tier: backend
spec:
  ports:
    - protocol: "TCP"
      port: 8090
      targetPort: http
  type: LoadBalancer
  selector:
    app: jmblog-api
    tier: backend
    version: v0.1.0-ci141